# todo remove cusomization for apparmor
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/apparmor_profile?
  value: ""

- type: replace
  path: /instance_groups/name=diego-cell/instances
  value: 1

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/disable_swap_limit?
  value: true
