// This file was generated by counterfeiter
package rpcfakes

import (
	"sync"

	"github.com/cppforlife/bosh-cpi-go/apiv1"
	"github.com/cppforlife/bosh-cpi-go/rpc"
)

type FakeActionFactory struct {
	CreateStub        func(string, apiv1.CallContext) (interface{}, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 string
		arg2 apiv1.CallContext
	}
	createReturns struct {
		result1 interface{}
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeActionFactory) Create(arg1 string, arg2 apiv1.CallContext) (interface{}, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 string
		arg2 apiv1.CallContext
	}{arg1, arg2})
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1, arg2)
	}
	return fake.createReturns.result1, fake.createReturns.result2
}

func (fake *FakeActionFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeActionFactory) CreateArgsForCall(i int) (string, apiv1.CallContext) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1, fake.createArgsForCall[i].arg2
}

func (fake *FakeActionFactory) CreateReturns(result1 interface{}, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *FakeActionFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeActionFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rpc.ActionFactory = new(FakeActionFactory)
